name: build

on:
  pull_request:

jobs:

  worker:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v4.1.0
    -
      name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
    -
      name: npm install
      run: npm install
    -
      name: hugo build
      run: npm run build
    -
      name: wrangler
      uses: cloudflare/wrangler-action@2.0.0
      with:
        environment: prd
        command: build
