name: imgcmp

on:
  push:
    
jobs:
  build:
    name: Optimize images
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: 9sako6/imgcmp@v2.0.3
      env:
        GITHUB_USER: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
